### ISSUE TITLE
Locale setting lost when changing subdomain

### ISSUE THREAD

**Issue by SimonGrn** [athyuttamre/locale-switcher#33] opened 2022-01-19 13:27 UTC
Hello,

since the rewrite, the locale setting is not kept when the subdomain changes in the tab. I don't understand why, it's completely breaking our workflow and we can't use this wonderful extension anymore :sob: 
Is it possible to have it back ? So that the tab doesn't lose the locale setting when the subdomain changes?

Thanks a lot!

**Comment by cupcakearmy** [comment] 2022-01-19 13:32
Hey there, thanks for the feedback!
I'd call it a duplicate of #29 and close it in favour of that. It's going to be back! :)

**Comment by SimonGrn** [comment] 2022-01-19 13:33
Thanks, but is this the same ? We were not using the global locale setting, just changing the locale, and change the URL and it was keeping the setting. Right now, it loses it...

**Closed as completed by cupcakearmy** 2022-01-19 13:32 UTC
Labels: duplicate
